### ISSUE TITLE
fallback mode for 512x256

### ISSUE THREAD

**Issue by desin24** [janbredenbeek/QED#2]

**Comment by desin24** [comment]
hello Jan
the should be a fallback mode so if QED is configured for 
SMSQE (big screen) it does not run properly on the standard screen

as for the config_bas
 OUTLN #0 ,SCR_XLIM,SCR_YLIM,0,0
helps a lot

**Comment by janbredenbeek** [comment]
The default window configured in the distributed binary was too large - the source code contains sensible values. But indeed QED should check the error code from SD.WDEF and act accordingly - todo.
